services:
  app:
    build: .
    container_name: echonote_app
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - API_KEY=${API_KEY}
      - WHATSAPP_URL=${WHATSAPP_URL}
      - MODEL_URL=${MODEL_URL}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/app
    runtime: nvidia
    extra_hosts:
      - "host.docker.internal:host-gateway"
