services:
  app:
    build: .
    container_name: echonote_app
    restart: unless-stopped
    ports:
      - "8002:8000"
    network_mode: "host"
    environment:
      - API_KEY=${API_KEY}
      - WHATSAPP_URL=${WHATSAPP_URL}
      - MODEL_URL=${MODEL_URL}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    extra_hosts:
      - "host.docker.internal:host-gateway"
